#!/usr/bin/env tsx
/**
 * Bundles src/widget/embed.ts → dist/embed.js (minified, sourcemap'd).
 *
 * The Worker reads dist/embed.js at module-load via a Wrangler text rule
 * and serves it under GET /embed.js (see src/routes/embed.ts).
 *
 * Targets ES2020 — broad enough for every browser shipping in 2026,
 * narrow enough to skip class-fields polyfills.
 */
import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const OUT_DIR = join(ROOT, "dist");
const OUT_FILE = join(OUT_DIR, "embed.js");
const EMBED_TS = join(ROOT, "src/widget/embed.bundled.ts");

mkdirSync(OUT_DIR, { recursive: true });

await build({
	entryPoints: [join(ROOT, "src/widget/embed.ts")],
	outfile: OUT_FILE,
	bundle: true,
	minify: true,
	format: "iife",
	platform: "browser",
	target: ["es2020"],
	sourcemap: true,
	legalComments: "none",
	logLevel: "info",
});

// Re-emit the bundle as a TS string export so the worker imports it as a
// regular module — no wrangler text-loader rule required of self-hosters.
// embed.bundled.ts is gitignored; it's a build artifact regenerated on
// every `npm run build:embed`.
const js = readFileSync(OUT_FILE, "utf8");
writeFileSync(
	EMBED_TS,
	`// AUTO-GENERATED by scripts/build-embed.ts — do not edit.
export const EMBED_JS = ${JSON.stringify(js)};
`,
);
console.log(`[build-embed] wrote ${EMBED_TS}`);
