#!/usr/bin/env tsx
/**
 * Bake the current package.json version into src/lib/version.gen.ts so the
 * Worker can know what version it's running without a runtime `fs` read
 * (which the Workers runtime doesn't allow).
 *
 * Called from build:assets. Output is gitignored.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");

const pkg: unknown = JSON.parse(
	readFileSync(join(REPO_ROOT, "package.json"), "utf8"),
);

if (
	typeof pkg !== "object" ||
	pkg === null ||
	typeof (pkg as { version?: unknown }).version !== "string"
) {
	console.error("[build:version] package.json has no version string");
	process.exit(1);
}

const version = (pkg as { version: string }).version;

const parseRepo = (): { owner: string; repo: string } => {
	const repoField = (pkg as { repository?: unknown }).repository;
	const url =
		typeof repoField === "string"
			? repoField
			: typeof repoField === "object" &&
					repoField !== null &&
					typeof (repoField as { url?: unknown }).url === "string"
				? (repoField as { url: string }).url
				: "";
	const m = url.match(/github\.com[:/]([^/]+)\/([^/.]+)/);
	if (m) return { owner: m[1] as string, repo: m[2] as string };
	return { owner: "KingPin", repo: "Garrul" };
};

const { owner, repo } = parseRepo();

const content = `// Generated by scripts/build-version.ts — do not edit.
export const CURRENT_VERSION = ${JSON.stringify(version)};
export const REPO_OWNER = ${JSON.stringify(owner)};
export const REPO_NAME = ${JSON.stringify(repo)};
`;

writeFileSync(join(REPO_ROOT, "src", "lib", "version.gen.ts"), content);
console.log(`[build:version] wrote src/lib/version.gen.ts (v${version})`);
