#!/usr/bin/env tsx
/**
 * Bundles AGENTS.md → src/agents.bundled.ts as a string constant.
 *
 * Substitutes the build-time {{VERSION}} placeholder with the current
 * git short SHA (or "dev" if unavailable). Request-time placeholders
 * ({{INSTANCE_URL}}, {{INSTANCE_HOST}}) are left untouched — the route
 * handler in src/routes/agents.ts substitutes them per request.
 *
 * Mirrors scripts/build-embed.ts so the worker imports AGENTS_MD as a
 * normal TS module — no wrangler text-loader rule required.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SRC = join(ROOT, "AGENTS.md");
const OUT = join(ROOT, "src/agents.bundled.ts");

let version = "dev";
try {
  // execFileSync — no shell, static args, no injection surface.
  version = execFileSync("git", ["rev-parse", "--short", "HEAD"], {
    cwd: ROOT,
    stdio: ["ignore", "pipe", "ignore"],
  })
    .toString()
    .trim();
} catch {
  // No git, or not a repo. Keep "dev".
}

const md = readFileSync(SRC, "utf8").replaceAll("{{VERSION}}", version);

writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/build-agents-md.ts — do not edit.
export const AGENTS_MD = ${JSON.stringify(md)};
`,
);
console.log(`[build-agents-md] wrote ${OUT} (version=${version})`);
