#!/usr/bin/env tsx
/**
 * Minify src/widget/styles.css into src/widget/styles.gen.ts.
 *
 * The widget injects its CSS as a string into a shadow root, so the CSS has
 * to reach the bundle as a JS string. It used to be a template literal in
 * embed.ts — which meant esbuild's minifier could not see it, and every
 * comment and indent was downloaded by every reader (5,335 bytes of comments
 * alone). Routing it through esbuild's CSS minifier instead saves ~2.7 KB
 * gzipped and lets the source stay as commented as it likes (#79).
 *
 * esbuild does the minifying rather than a hand-rolled regex on purpose: it
 * parses the CSS, so it will not mangle a `content:` string or a data URI.
 *
 * Wired as `prebuild:embed` rather than as one more step in build:assets, so
 * that a bare `npm run build:embed` on a fresh checkout still resolves the
 * generated import instead of failing on it. Output is gitignored.
 */
import { transform } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const SRC = join(REPO_ROOT, "src/widget/styles.css");
const OUT = join(REPO_ROOT, "src/widget/styles.gen.ts");

const css = readFileSync(SRC, "utf8");

const result = await transform(css, {
	loader: "css",
	minify: true,
	logLevel: "warning",
});

// A CSS parse problem downgrades to a warning and passes the offending bytes
// through, which would ship broken styles quietly. The widget's entire visual
// surface is this one file — fail loudly instead.
if (result.warnings.length > 0) {
	console.error("[build:styles] esbuild reported CSS warnings:");
	for (const w of result.warnings) {
		const at = w.location ? `${SRC}:${w.location.line}` : SRC;
		console.error(`  ${at} — ${w.text}`);
	}
	process.exit(1);
}

if (result.code.trim().length === 0) {
	console.error("[build:styles] minified CSS is empty — refusing to write.");
	process.exit(1);
}

writeFileSync(
	OUT,
	`// Generated by scripts/build-styles.ts from styles.css — do not edit.
export const STYLE_CSS: string = ${JSON.stringify(result.code)};
`,
);

const kb = (n: number) => (n / 1024).toFixed(2);
console.log(
	`[build:styles] wrote src/widget/styles.gen.ts ` +
		`(${kb(css.length)} KB → ${kb(result.code.length)} KB)`,
);
